mult = int(input('Me dê um número:'))
print('-'*15)
print('{} x {} = {}'.format(mult, 1, mult*1))
print('{} x {} = {}'.format(mult, 2, mult*2))
print('{} x {} = {}'.format(mult, 3, mult*3))
print('{} x {} = {}'.format(mult, 4, mult*4))
print('{} x {} = {}'.format(mult, 5, mult*5))
print('{} x {} = {}'.format(mult, 6, mult*6))
print('{} x {} = {}'.format(mult, 7, mult*7))
print('{} x {} = {}'.format(mult, 8, mult*8))
print('{} x {} = {}'.format(mult, 9, mult*9))
print('{} x {} = {}'.format(mult, 10, mult*10))
print( '-'*15)